<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4N5rxxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4N5rxxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4N5rxxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4N5rxxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4N5rxxs\App_KernelDevDebugContainer([
    'container.build_hash' => '4N5rxxs',
    'container.build_id' => '0d8bcdde',
    'container.build_time' => 1620336959,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4N5rxxs');
