<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHR9FanQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHR9FanQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHR9FanQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHR9FanQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHR9FanQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HR9FanQ',
    'container.build_id' => '2713854a',
    'container.build_time' => 1619354325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHR9FanQ');
