<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/Admin']], [], []],
    'ajouterAgence' => [[], ['_controller' => 'App\\Controller\\AgenceController::ajouterAgence'], [], [['text', '/agence/ajouter']], [], []],
    'consulterAgence' => [['id'], ['_controller' => 'App\\Controller\\AgenceController::consulterAgence'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/agence/consulter']], [], []],
    'modifierAgence' => [['id'], ['_controller' => 'App\\Controller\\AgenceController::modifierAgence'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/agence/modifier']], [], []],
    'supprimerAgence' => [['id'], ['_controller' => 'App\\Controller\\AgenceController::supprimerAgence'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/agence/supprimer']], [], []],
    'ajouterVoiture' => [[], ['_controller' => 'App\\Controller\\VoitureController::ajouterVoiture'], [], [['text', '/voiture/ajouter']], [], []],
    'consulterVoiture' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::consulterVoiture'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/consulter']], [], []],
    'modifierVoiture' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::modifierVoiture'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Voiture/modifier']], [], []],
    'supprimerVoiture' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::supprimerVoiture'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/supprimer']], [], []],
];
